#!/usr/bin/env python
from RPIO import PWM

# Oscillate the pwms
ports = []
servo = PWM.Servo()
for p in ports:
    servo.set_servo(p, PWM.PULSE_WIDTH_INCREMENT_GRANULARITY_US_DEFAULT)
while True:
    pass

