#!/usr/bin/env bash
set -e
set -x

function clean_up {
    # Only works on gnu-ps
    # Kill all the children
    ps --pid $$ | tail -n +1 | awk '{print $1}' | xargs kill
}

trap clean_up SIGHUP SIGINT SIGTERM
# Compile whetstone and run it
mkdir -p tmp
cd tmp
wget http://www.roylongbottom.org.uk/Raspberry_Pi_Benchmarks.zip
unzip -n Raspberry_Pi_Benchmarks.zip
cd Raspberry_Pi_Benchmarks
chmod +x whetstonePiA6
chmod +x dhrystonePiA6
chmod +x busspeedPiA6
chmod +x memspeedPiA6

while [ 0 -eq 0 ]
do
    # Stupid tests want you to hit enter
    echo -e "\n" | ./whetstonePiA6
    echo -e "\n" | ./dhrystonePiA6
    # This test returns 1... not clear why
    set +e
    echo -e "\n" | ./busspeedPiA6
    echo -e "\n" | ./memspeedPiA6
    set -e
done
cd ../../
rm -rf tmp
