#!/usr/bin/env bash
set -e
set -x

# Compile whetstone and run it
mkdir tmp
cd tmp
wget http://www.roylongbottom.org.uk/Raspberry_Pi_Benchmarks.zip
unzip Raspberry_Pi_Benchmarks.zip
cd Raspberry_Pi_Benchmarks
chmod +x whetstonePiA6
./whetstonePiA6
chmod +x dhrystonePiA6
./dhrystonePiA6
chmod +x busspeedPiA6
./busspeedPiA6
chmod +x memspeedPiA6
./memspeedPiA6

